services:
  db:
    image: mariadb
    env_file: .env
    volumes:
      - ./docker/db/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - app-network

  node-service:
    build: ./docker/api
    env_file: .env
    environment:
      DB_HOST: ${DB_HOST}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db
    networks:
      - app-network

  nginx:
    build: ./docker/nginx
    ports:
      - "8080:80"
    depends_on:
      - node-service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
